### PR TITLE
"We hope offer" into "We hope to offer"

### PR DESCRIPTION
**Pull request by aretecode**

### CODE REVIEW

**Comment by bergie** [comment]
@aretecode thanks!

**Comment by aretecode** [comment]
@bergie 

I've been working a project for years that is quite similar! It's my specialization; it's what I love doing; it's my life's passion. I'd like to get to know your team & project better, what is the best way to interact with you?

**Comment by TukuTuru** [comment]
can I see a actual site using this ?

Why is it stated it will be available in some date in the past, but it is actually not ?
https://thegrid.io

*Be Founding Member #55705
Really? If there where 55K users I think there would be at least ONE user providing example links ?
*1 year pre-paid subscription to The Grid
*Currently in closed beta with a limited number of Founding Members
You state this since 5 months, I even read somewhere you launch june the 8th, 2015. 
*Subscription begins when beta testing is complete
Oh, really? and when is that going to be? 
*Locked-in rate of $8/month (regularly $25)
*7 different sites with hosting
7x50K users == there MUST be somebody who can provide a example site unless grid.io!!!
*Custom domain support
*Premium contributors, storage and bandwidth
*Commerce engine when available
*Limited-edition Grid NFC Token


I assume this will in a close future be declared as one of the most raffinate Internet Hoaxes ever?


And even if it's not, I would NEVER want to have a Site using HTML like yours.

How could I even take control of how and what's displayed?

Does grid read my mind?

Ohhh guys...

I respect you for the idea of how to make money though :P

**Comment by bergie** [comment]
@aretecode cool! Please get in touch. You'll find my details on the GitHub profile or http://bergie.iki.fi

(also, removed the comment that was unrelated to this pull request)

**Pull request merged**
